import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yeo Yi Xin Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <head>
        <meta name="image" property="og:image" content="My_portfolio.png" />
        <meta
          name="title"
          property="og:title"
          content="Yeo Yi Xin's Portfolio"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
